class Product {
  constructor(
    slug,
    name,
    productCode,
    price,
    description,
    longDescription,
    imageUrls,
    // altProducts,
    productURL,
    category,
  ) {
    this.slug = slug;
    this.name = name;
    this.ProductCode = productCode;
    this.price = price;
    this.description = description;
    this.longDescription = longDescription;
    this.imageUrls = imageUrls; //Array of image URLS
    // this.altProducts = altProducts; //Array of alternative products
    this.productURL = productURL;
    this.category = category;
  }
}

const products = [
  new Product(
    "RosaTheLabrador4inchx6inch(4R)Print",
    "Rosa The Labrador 4 inch x 6 inch (4R) Print",
    "Rosa_Lab_4X6-PRINT",
    14.99,
    "A 4 inch by 6 inch Giclee Print of Rosa The Labrador, printed on high-quality paper with vibrant colours. Perfect for framing and displaying in your home or office.",
    "This is a long Description",
    [
      "/images/Rosa_Labrador/Full_Painting.jpg",
      "/images/Rosa_Labrador/Close_Up_Belly.jpg",
      "/images/Rosa_Labrador/Close_Up_Chest.jpg",
      "/images/Rosa_Labrador/Close_Up_Face.jpg",
      "/images/Rosa_Labrador/Rosa the Labrador QR Code.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),
  new Product(
    "RosaTheLabrador5inchx7inchPrint",
    "Rosa The Labrador 5 inch x 7 inch Print",
    "Rosa_Lab_5X7-PRINT",
    17.99,
    "A 5 inch by 7 inch Giclee Print of Rosa The Labrador, printed on high-quality paper with vibrant colours. Perfect for framing and displaying in your home or office.",
    "This is a long Description",
    [
      "/images/Rosa_Labrador/Full_Painting.jpg",
      "/images/Rosa_Labrador/Close_Up_Belly.jpg",
      "/images/Rosa_Labrador/Close_Up_Chest.jpg",
      "/images/Rosa_Labrador/Close_Up_Face.jpg",
      "/images/Rosa_Labrador/Rosa the Labrador QR Code.jpg",
    ],
    "https://square.link/u/4yzuxH2u",
  ),
  new Product(
    "RosaTheLabrador10inchx8inch(A4)Print",
    "Rosa The Labrador 10 inch x 8 inch (A4) Print",
    "Rosa_Lab_0A4-PRINT",
    34.99,
    "A 10 inch by 8 inch (A4) Giclee Print of Rosa The Labrador, printed on high-quality paper with vibrant colours. Perfect for framing and displaying in your home or office.",
    "This is a long Description",
    [
      "/images/Rosa_Labrador/Full_Painting.jpg",
      "/images/Rosa_Labrador/Close_Up_Belly.jpg",
      "/images/Rosa_Labrador/Close_Up_Chest.jpg",
      "/images/Rosa_Labrador/Close_Up_Face.jpg",
      "/images/Rosa_Labrador/Rosa the Labrador QR Code.jpg",
    ],
    "https://square.link/u/0zeABJtV",
  ),
  new Product(
    "RosaTheLabradorA3",
    "Rosa The Labrador A3",
    "Rosa_Lab_0A3-PRINT",
    46.99,
    "An A3 Giclee Print of Rosa The Labrador, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    "This is a long Description",
    [
      "/images/Rosa_Labrador/Full_Painting.jpg",
      "/images/Rosa_Labrador/Close_Up_Belly.jpg",
      "/images/Rosa_Labrador/Close_Up_Chest.jpg",
      "/images/Rosa_Labrador/Close_Up_Face.jpg",
      "/images/Rosa_Labrador/Rosa the Labrador QR Code.jpg",
    ],
    "https://square.link/u/nIYnDih5",
  ),
  new Product(
    "RosaTheLabradorA2",
    "Rosa The Labrador A2",
    "Rosa_Lab_0A2-PRINT",
    54.99,
    "An A2 Giclee Print of Rosa The Labrador, printed on high-quality paper with vibrant colours. Perfect for framing and displaying in your home or office.",
    "This is a long Description",
    [
      "/images/Rosa_Labrador/Full_Painting.jpg",
      "/images/Rosa_Labrador/Close_Up_Belly.jpg",
      "/images/Rosa_Labrador/Close_Up_Chest.jpg",
      "/images/Rosa_Labrador/Close_Up_Face.jpg",
      "/images/Rosa_Labrador/Rosa the Labrador QR Code.jpg",
    ],
    "https://square.link/u/NjOMbrIa",
  ),

  //From here down is all duplicated of above
  new Product(
    "MaximusA5GicleePrints",
    "Poodle A5 Giclee Print of Maximus",
    "P1004A24",
    54.95,
    "A4 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    "This is a long Description",
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
    "Poodle",
  ),

  new Product(
    "MaximusA6GicleePrints",
    "Poodle A6 Giclee Print of Maximus",
    "P1004A29",
    64.95,
    "A3 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office. TSTSTSTSTSTSTSTSTS tststststst tststs tststs tstst ststs stststststst",
    "This is a long Description",
    [
      "/images/barn owl.jpg",
      "/images/Black and White.jpg",
      "/images/cheetah.jpg",
      "/images/Fox.jpg",
      "/images/Parrot.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
    "Poodle",
  ),

  new Product(
    "MaximusA4GicleePrints",
    "Beautiful A4 Giclee Print of Maximus",
    "P1004A24",
    54.95,
    "A4 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    "This is a long Description",
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
    "Dalmation",
  ),

  new Product(
    "MaximusA8GicleePrints",
    `Poodle A8 Giclee Print of Maximus`,
    "P1004A21",
    84.95,
    "A1 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    `This is the long description`,
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
    "Poodle",
  ),
  new Product(
    "MaximusA9GicleePrints",
    "Beautiful A9 Giclee Print of Maximus",
    "P1004A24",
    54.95,
    "A4 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    "This is a long Description",
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),

  new Product(
    "MaximusA10GicleePrints",
    "Beautiful A10 Giclee Print of Maximus",
    "P1004A29",
    64.95,
    "A3 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office. TSTSTSTSTSTSTSTSTS tststststst tststs tststs tstst ststs stststststst",
    "This is a long Description",
    [
      "/images/barn owl.jpg",
      "/images/Black and White.jpg",
      "/images/cheetah.jpg",
      "/images/Fox.jpg",
      "/images/Parrot.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),

  new Product(
    "MaximusA11GicleePrints",
    `Beautiful A11 Giclee Print of Maximus`,
    "P1004A22",
    74.95,
    "A2 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    `This is the long description`,
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),
  new Product(
    "MaximusA12GicleePrints",
    `Beautiful A12 Giclee Print of Maximus`,
    "P1004A21",
    84.95,
    "A1 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    `This is the long description`,
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),
  new Product(
    "MaximusA13GicleePrints",
    "Beautiful A13 Giclee Print of Maximus",
    "P1004A24",
    54.95,
    "A4 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    "This is a long Description",
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),

  new Product(
    "MaximusA14GicleePrints",
    "Beautiful A14 Giclee Print of Maximus",
    "P1004A29",
    64.95,
    "A3 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office. TSTSTSTSTSTSTSTSTS tststststst tststs tststs tstst ststs stststststst",
    "This is a long Description",
    [
      "/images/barn owl.jpg",
      "/images/Black and White.jpg",
      "/images/cheetah.jpg",
      "/images/Fox.jpg",
      "/images/Parrot.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),

  new Product(
    "MaximusA15GicleePrints",
    `Beautiful A15 Giclee Print of Maximus`,
    "P1004A22",
    74.95,
    "A2 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    `This is the long description`,
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),
  new Product(
    "MaximusA16GicleePrints",
    `Beautiful A16 Giclee Print of Maximus`,
    "P1004A21",
    84.95,
    "A1 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    `This is the long description`,
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),
  new Product(
    "MaximusA17GicleePrints",
    "Beautiful A17 Giclee Print of Maximus",
    "P1004A24",
    54.95,
    "A4 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    "This is a long Description",
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),

  new Product(
    "MaximusA18GicleePrints",
    "Beautiful A18 Giclee Print of Maximus",
    "P1004A29",
    64.95,
    "A3 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office. TSTSTSTSTSTSTSTSTS tststststst tststs tststs tstst ststs stststststst",
    "This is a long Description",
    [
      "/images/barn owl.jpg",
      "/images/Black and White.jpg",
      "/images/cheetah.jpg",
      "/images/Fox.jpg",
      "/images/Parrot.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),

  new Product(
    "MaximusA19GicleePrints",
    `Beautiful A19 Giclee Print of Maximus`,
    "P1004A22",
    74.95,
    "A2 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    `This is the long description`,
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),
  new Product(
    "MaximusA20GicleePrints",
    `Beautiful A20 Giclee Print of Maximus`,
    "P1004A21",
    84.95,
    "A1 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    `This is the long description`,
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),
  new Product(
    "MaximusA21GicleePrints",
    "Beautiful A21 Giclee Print of Maximus",
    "P1004A24",
    54.95,
    "A4 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    "This is a long Description",
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),

  new Product(
    "MaximusA22GicleePrints",
    "Beautiful A22 Giclee Print of Maximus",
    "P1004A29",
    64.95,
    "A3 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office. TSTSTSTSTSTSTSTSTS tststststst tststs tststs tstst ststs stststststst",
    "This is a long Description",
    [
      "/images/barn owl.jpg",
      "/images/Black and White.jpg",
      "/images/cheetah.jpg",
      "/images/Fox.jpg",
      "/images/Parrot.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),

  new Product(
    "MaximusA23GicleePrints",
    `Beautiful A23 Giclee Print of Maximus`,
    "P1004A22",
    74.95,
    "A2 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    `This is the long description`,
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),
  new Product(
    "MaximusA24GicleePrints",
    `Beautiful A24 Giclee Print of Maximus`,
    "P1004A21",
    84.95,
    "A1 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    `This is the long description`,
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),
];

module.exports = products;
