class Product {
  constructor(
    slug,
    name,
    productCode,
    price,
    description,
    longDescription,
    imageUrls,
    // altProducts,
    productURL,
  ) {
    this.slug = slug;
    this.name = name;
    this.ProductCode = productCode;
    this.price = price;
    this.description = description;
    this.longDescription = longDescription;
    this.imageUrls = imageUrls; //Array of image URLS
    // this.altProducts = altProducts; //Array of alternative products
    this.productURL = productURL;
  }
}

const products = [
  new Product(
    "MaximusA4GicleePrints",
    "Beautiful A4 Giclee Print of Maximus",
    "P1004A24",
    54.95,
    "A4 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    "This is a long Description",
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),

  new Product(
    "MaximusA3GicleePrints",
    "Beautiful A3 Giclee Print of Maximus",
    "P1004A29",
    64.95,
    "A3 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office. TSTSTSTSTSTSTSTSTS tststststst tststs tststs tstst ststs stststststst",
    "This is a long Description",
    [
      "/images/barn owl.jpg",
      "/images/Black and White.jpg",
      "/images/cheetah.jpg",
      "/images/Fox.jpg",
      "/images/Parrot.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),

  new Product(
    "MaximusA2GicleePrints",
    `Beautiful A2 Giclee Print of Maximus`,
    "P1004A22",
    74.95,
    "A2 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    `This is the long description`,
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),
  new Product(
    "MaximusA1GicleePrints",
    `Beautiful A1 Giclee Print of Maximus`,
    "P1004A21",
    84.95,
    "A1 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    `This is the long description`,
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),

  //From here down is all duplicated of above
  new Product(
    "MaximusA5GicleePrints",
    "Beautiful A5 Giclee Print of Maximus",
    "P1004A24",
    54.95,
    "A4 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    "This is a long Description",
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),

  new Product(
    "MaximusA6GicleePrints",
    "Beautiful A6 Giclee Print of Maximus",
    "P1004A29",
    64.95,
    "A3 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office. TSTSTSTSTSTSTSTSTS tststststst tststs tststs tstst ststs stststststst",
    "This is a long Description",
    [
      "/images/barn owl.jpg",
      "/images/Black and White.jpg",
      "/images/cheetah.jpg",
      "/images/Fox.jpg",
      "/images/Parrot.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),

  new Product(
    "MaximusA7GicleePrints",
    `Beautiful A7 Giclee Print of Maximus`,
    "P1004A22",
    74.95,
    "A2 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    `This is the long description`,
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),
  new Product(
    "MaximusA8GicleePrints",
    `Beautiful A8 Giclee Print of Maximus`,
    "P1004A21",
    84.95,
    "A1 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    `This is the long description`,
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),
  new Product(
    "MaximusA9GicleePrints",
    "Beautiful A9 Giclee Print of Maximus",
    "P1004A24",
    54.95,
    "A4 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    "This is a long Description",
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),

  new Product(
    "MaximusA10GicleePrints",
    "Beautiful A10 Giclee Print of Maximus",
    "P1004A29",
    64.95,
    "A3 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office. TSTSTSTSTSTSTSTSTS tststststst tststs tststs tstst ststs stststststst",
    "This is a long Description",
    [
      "/images/barn owl.jpg",
      "/images/Black and White.jpg",
      "/images/cheetah.jpg",
      "/images/Fox.jpg",
      "/images/Parrot.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),

  new Product(
    "MaximusA11GicleePrints",
    `Beautiful A11 Giclee Print of Maximus`,
    "P1004A22",
    74.95,
    "A2 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    `This is the long description`,
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),
  new Product(
    "MaximusA12GicleePrints",
    `Beautiful A12 Giclee Print of Maximus`,
    "P1004A21",
    84.95,
    "A1 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    `This is the long description`,
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),
  new Product(
    "MaximusA13GicleePrints",
    "Beautiful A13 Giclee Print of Maximus",
    "P1004A24",
    54.95,
    "A4 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    "This is a long Description",
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),

  new Product(
    "MaximusA14GicleePrints",
    "Beautiful A14 Giclee Print of Maximus",
    "P1004A29",
    64.95,
    "A3 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office. TSTSTSTSTSTSTSTSTS tststststst tststs tststs tstst ststs stststststst",
    "This is a long Description",
    [
      "/images/barn owl.jpg",
      "/images/Black and White.jpg",
      "/images/cheetah.jpg",
      "/images/Fox.jpg",
      "/images/Parrot.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),

  new Product(
    "MaximusA15GicleePrints",
    `Beautiful A15 Giclee Print of Maximus`,
    "P1004A22",
    74.95,
    "A2 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    `This is the long description`,
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),
  new Product(
    "MaximusA16GicleePrints",
    `Beautiful A16 Giclee Print of Maximus`,
    "P1004A21",
    84.95,
    "A1 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    `This is the long description`,
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),
  new Product(
    "MaximusA17GicleePrints",
    "Beautiful A17 Giclee Print of Maximus",
    "P1004A24",
    54.95,
    "A4 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    "This is a long Description",
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),

  new Product(
    "MaximusA18GicleePrints",
    "Beautiful A18 Giclee Print of Maximus",
    "P1004A29",
    64.95,
    "A3 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office. TSTSTSTSTSTSTSTSTS tststststst tststs tststs tstst ststs stststststst",
    "This is a long Description",
    [
      "/images/barn owl.jpg",
      "/images/Black and White.jpg",
      "/images/cheetah.jpg",
      "/images/Fox.jpg",
      "/images/Parrot.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),

  new Product(
    "MaximusA19GicleePrints",
    `Beautiful A19 Giclee Print of Maximus`,
    "P1004A22",
    74.95,
    "A2 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    `This is the long description`,
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),
  new Product(
    "MaximusA20GicleePrints",
    `Beautiful A20 Giclee Print of Maximus`,
    "P1004A21",
    84.95,
    "A1 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    `This is the long description`,
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),
  new Product(
    "MaximusA21GicleePrints",
    "Beautiful A21 Giclee Print of Maximus",
    "P1004A24",
    54.95,
    "A4 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    "This is a long Description",
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),

  new Product(
    "MaximusA22GicleePrints",
    "Beautiful A22 Giclee Print of Maximus",
    "P1004A29",
    64.95,
    "A3 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office. TSTSTSTSTSTSTSTSTS tststststst tststs tststs tstst ststs stststststst",
    "This is a long Description",
    [
      "/images/barn owl.jpg",
      "/images/Black and White.jpg",
      "/images/cheetah.jpg",
      "/images/Fox.jpg",
      "/images/Parrot.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),

  new Product(
    "MaximusA23GicleePrints",
    `Beautiful A23 Giclee Print of Maximus`,
    "P1004A22",
    74.95,
    "A2 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    `This is the long description`,
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),
  new Product(
    "MaximusA24GicleePrints",
    `Beautiful A24 Giclee Print of Maximus`,
    "P1004A21",
    84.95,
    "A1 Giclee Print of Maximus, printed on high-quality paper with vibrant colors. Perfect for framing and displaying in your home or office.",
    `This is the long description`,
    [
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
      "/images/Black and White.jpg",
    ],
    "https://square.link/u/DMuQ7K3Q",
  ),
];

module.exports = products;
